# HEADER VERIFICATION
text1 = "Upcoming scheduled maintenance"
text2 = "By proceeding, you acknowledge that you have read our Terms of use and Privacy statement and agree to be bound by them."
text3 = "Log in"
text4 = "Use another authentication"
text5 = "Check your certificates"
text6 = "Identity details confirmed"
text7 = "Set a new 6-digit Singpass app passcode"
text8 = "Singpass app has been successfully set up!"
text9 = "Scan or tap QR code to log in"
text10 = "Welcome back,"
text11 = "Welcome to Singpass app – your new 2FA."
text12 = "Enter the 6-digit One-time Password"
text13 = "Home"
text14 = "Scan"
text15 = "Inbox"
text16 = "Great! Re-enter your Singpass app passcode to confirm."