service: JS-websocket

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x


functions:
  connectionHandler:
    handler: handler.connectionHandler
    events:
    - websocket:
        route: $connect
    - websocket:
        route: $disconnect
  sendMessageHandler:
    handler: handler.sendMessageHandler
    events:
      - websocket:
          route: sendMessage
